### ISSUE TITLE
 Custom New Tab page background not working as expected on Firefox Nightly #20 

### ISSUE THREAD

**Issue by Danilol69** [Bali10050/FirefoxCSS#21]
The last commit fixed my previous issue but it shows only a cut out version of the picture in the new tab, idk if this is expected or not

![image](https://github.com/user-attachments/assets/130f57aa-f84e-448e-8dbe-9bfd80d82ce7)
![image](https://github.com/user-attachments/assets/3b682038-18da-40e1-8ce2-fe7767be9f4f)

Its not really a problem it would just be nice to see the full picture

**Comment by Bali10050** [comment]
This is the best way to make the navigator-toolbox and newtab page look like they have the same background, without overcomplicating things. I recommend adding this to the end of your `userContent.css`, if you only plan to have the background for your newtab page:

```css
@-moz-document url("about:newtab"), url("about:home"){.outer-wrapper.ds-outer-wrapper-breakpoint-override.only-search.visible-logo{background-size: cover !important}}
```
