### ISSUE TITLE
Only one address bar search suggestion visible

### ISSUE THREAD

**Issue by Terrance** [Bali10050/FirefoxCSS#22]
Using stock Firefox styles:

![image](https://github.com/user-attachments/assets/fdcc9dd3-e9fd-4eb5-80db-e0cf59f9f7e7)

Using the `alt` branch of FirefoxCSS's `chrome`:

![image](https://github.com/user-attachments/assets/d7272724-3cdc-4406-beed-edf02578f06f)

I'm not sure if this is a config issue despite not using the `user.js` -- can't see anything specific to controlling the overall result count.

**Comment by Bali10050** [comment]
The number of search results is controlled in this block of code, [which are currently the lines 77-80 in the `userChrome.css`](https://github.com/Bali10050/FirefoxCSS/blob/1bf723ab9e3709ee4ca363cf6d1bec2ae631ca33/chrome/userChrome.css#L77C1-L80C66):
```css
/*  Urlbar popup thing  */
.urlbarView-row{display: none !important}
.urlbarView-row:nth-child(1), .urlbarView-row:nth-child(2){display: flex !important}
#urlbar-anon-search-settings{margin-inline-start: 0px !important}
```

***

This one should remove all search suggestions: 
```css
.urlbarView-row{display: none !important}
```

And this one makes the first two visible:
```css
.urlbarView-row:nth-child(1), .urlbarView-row:nth-child(2){display: flex !important}
```
